import { Image } from "react-native";
import Colors from "./Colors";
import Fonts from "./Fonts";
import images from "./Images";

export const Android_Theme_Light = {

  //COMMON COLORS
  WHITE_COLOR: Colors.WHITE,
  BLACK_COLOR: Colors.BLACK,
  BACKGROUND_COLOR: Colors.BLUE_ACCENT,
  SAFEAREA_BACKGROUND_COLOR: Colors.BLUE_ACCENT,
  COMMON_BUTTON_BACKGROUND_COLOR: Colors.Dark_Blue,
  DEEP_BLACK_COLOR: Colors.DEEP_BLACK_COLOR,
  DARK_GRAY_COLOR: Colors.DARK_GRAY_COLOR,
  GRAY_COLOR : Colors.GRAY,
  BLUE_COLOR : Colors.Blue,
  LIGHT_BLUE_COLOR: Colors.LIGHT_Blue,
  DARK_GREEN_COLOR: Colors.GREEN_DARK,
  DARK_BLUE_COLOR: Colors.Dark_Blue,

  //OTHER COLORS
  SPLASH_BOTTOM_COLOR: Colors.SPLASH_BOTTOM_COLOR,

  //FONT TYPES
  POPPINS_THIN: Fonts.POPPINS_THIN,
  POPPINS_LIGHT: Fonts.POPPINS_LIGHT,
  POPPINS_REGULAR: Fonts.POPPINS_REGULAR,
  POPPINS_MEDIUM: Fonts.POPPINS_MEDIUM,
  POPPINS_SEMIBOLD: Fonts.POPPINS_SEMIBOLD,
  POPPINS_BOLD: Fonts.POPPINS_BOLD,
  POPPINS_EXTRABOLD: Fonts.POPPINS_EXTRABOLD,
  POPPINS_THINITALIC: Fonts.POPPINS_THINITALIC,
  POPPINS_LIGHTITALIC: Fonts.POPPINS_LIGHTITALIC,
  POPPINS_MEDIUM_ITALIC: Fonts.POPPINS_MEDIUM_ITALIC,
  POPPINS_SEMIBOLD_ITALIC: Fonts.POPPINS_SEMIBOLD_ITALIC,
  POPPINS_BOLD_ITALIC: Fonts.POPPINS_BOLD_ITALIC,
  POPPINS_EXTRABOLD_ITALIC: Fonts.POPPINS_EXTRABOLD_ITALIC,

  
  //FONT SIZES
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_SIZE_HEADER_ONE: 25,
  FONT_SIZE_HEADER_TWO: 20,

  FONT_SIZE_HEADER_ONE_MEDIUM: 40,
  FONT_SIZE_HEADER_TWO_MEDIUM: 24,
  FONT_SIZE_HEADER_THREE_MEDIUM: 20,
  FONT_SIZE_CAPTION_ONE_MEDIUM: 12,
  FONT_SIZE_BODY_ONE_REGULAR: 16,
  FONT_SIZE_BODY_ONE_MEDIUM: 16,
  FONT_SIZE_BODY_TWO_REGULAR: 14,
  FONT_SIZE_BODY_TWO_MEDIUM: 14,
  FONT_SIZE_HEADER_THREE_BOLD: 20,
  
  FONT_SIZE_10: 10,
  FONT_SIZE_18: 18,
  FONT_SIZE_15: 15,
  FONT_SIZE_30: 30,


  //Text Style Colors
  TextStyleH1Color : Colors.DEEP_BLACK_COLOR,
  TextStyleH3Color: Colors.BLACK_DEEP,
  TextStyleCaptionColor: Colors.DARK_GRAY_COLOR,
  TextStyleH1MediumColor : Colors.GRAY,
  TEXTSTYLE_BODY_COLOR : Colors.GRAY,

  //SVG ICONS
  ICON_BACK_ARROW : images.ICON_BACK_ARROW_ANDROID_LIGHT,
  ICON_VERIFIED : images.ICON_VERIFIED_ANDROID_LIGHT,
  ICON_VIEW_PASSWORD: images.ICON_VIEW_PASSWORD_ANDROID_LIGHT,
  ICON_NIC : images.ICON_VIEW_NIC_ANDROID_LIGHT,
  ICON_CALENDER : images.ICON_CALENDER_ANDROID_LIGHT,
  ICON_DROPDOWN : images.ICON_DROPDOWN_ANDROID_LIGHT,
  ICON_LOCK : images.ICON_LOCK_ANDROID_LIGHT,
  ICON_FORWARD : images.ICON_FORWARD_ANDROID_LIGHT,
  ICON_MAIL :images.ICON_MAIL_ANDROID_LIGHT,
  ICON_CIRCLECHECKED: images.ICON_CIRCLECHECKED_ANDROID_LIGHT,
  ICON_MI_LOGO_DESCRIPTION_ANDROID : images.ICON_MI_LOGO_DESCRIPTION_ANDROID_LIGHT ,
  ICON_CAMERA :images.ICON_CAMERA_ANDROID_LIGHT,
  ICON_CIRCLE_X : images.ICON_CIRCLE_X_ANDROID_LIGHT,
  ICON_DRAWERMENU : images.ICON_DRAWERMENU_ANDROID_LIGHT,
  ICON_SEND : images.ICON_SEND_ANDROID_LIGHT,
  ICON_INVEST: images.ICON_INVEST_ANDROID_LIGHT,
  ICON_PAYMENT : images.ICON_PAYMENT_ANDROID_LIGHT,
  ICON_LOAN : images.ICON_LOAN_ANDROID_LIGHT,
  ICON_EXTERNALOPEN : images.ICON_EXTERNALOPEN_ANDROID_LIGHT,
  ICON_SAVINGS : images.ICON_SAVINGS_ANDROID_LIGHT,
  ICON_PLUS:images.ICON_PLUS_ANDROID_LIGHT,
  ICON_PAYNOW : images.ICON_PAYNOW_ANDROID_LIGHT,
  ICON_BILLER_MANAGEMENT : images.ICON_BILLER_MANAGEMENT_ANDROID_LIGHT,
  ICON_FORWARD_NAVIGATE  : images.ICON_FORWARD_NAVIGATE_ANDROID_LIGHT,
  ICON_PLUS: images.ICON_PLUS_ANDROID_LIGHT,
  ICON_SPLASH_BOTTOM: images.ICON_SPLASH_BOTTOM_ANDROID_LIGHT,
  MI_LOGO: images.MI_LOGO,
  ICON_PAYMENT : images.ICON_PAYMENT_ANDROID_LIGHT,
  ICON_LOAN : images.ICON_LOAN_ANDROID_LIGHT,
  ICON_EXTERNALOPEN : images.ICON_EXTERNALOPEN_ANDROID_LIGHT,
  ICON_SAVINGS : images.ICON_SAVINGS_ANDROID_LIGHT,
  ICON_PLUS:images.ICON_PLUS_ANDROID_LIGHT,
  ICON_PAYNOW : images.ICON_PAYNOW_ANDROID_LIGHT,
  ICON_BILLER_MANAGEMENT : images.ICON_BILLER_MANAGEMENT_ANDROID_LIGHT,
  ICON_FORWARD_NAVIGATE  : images.ICON_FORWARD_NAVIGATE_ANDROID_LIGHT,
  ICON_PLUS: images.ICON_PLUS_ANDROID_LIGHT,
  ICON_BACK_ARROWS : images.ICON_BACK_ARROWS_ANDROID_LIGHT,
  ICON_HOME : images.ICON_HOME_ANDROID_LIGHT,
  ICON_DOWN_ARROW : images.ICON_DOWN_ARROW_ANDROID_LIGHT,
  BACKGROUND_DROPDOWN_SELECT : images.BACKGROUND_DROPDOWN_SELECT,
  ICON_SEARCH : images.ICON_SEARCH_ANDROID_LIGHT,
  ICON_GOLDLOAN : images.ICON_GOLDLOAN_ANDROID_LIGHT,
  ICON_FINGER_PRINT : images.ICON_FINGER_PRINT_LIGHT,
  ICON_LOG_OUT : images.ICON_LOG_OUT_ANDROID_LIGHT,
  ICON_POWER: images.ICON_POWER_ANDROID_LIGHT,
  ICON_INFO : images.ICON_INFO_ANDROID_LIGHT,
  ICON_BELL: images.ICON_BELL_ANDROID_LIGHT,
  ICON_BELL: images.ICON_BELL_IOS_LIGHT,
  ICON_SEND_ARROW : images.ICON_SEND_ARROW_ANDROID_LIGHT,
  ICON_RECEIVE_ARROW : images.ICON_RECEIVE_ARROW_ANDROID_LIGHT,
  ICON_SETTINGS : images.ICON_SETTINGS_ANDROID_LIGHT,
  ICON_PAYEE_MANAGEMENT : images.ICON_PAYEE_MANAGEMET_ANDROID_LIGHT,
  ICON_ADD_ACCOUNT : images.ICON_ADD_ACCOUNTS_ANDROID_LIGHT,
  ICON_QR : images.ICON_QR_ANDROID_LIGHT,
  ICON_EASY_PAYMENT : images.ICON_EASY_PAYMENT_ANDROID_LIGHT,
  ICON_MORE : images.ICON_MORE_ANDROID_LIGHT,

  IMAGE_PROFILE_PIC : images.IMAGE_PROFILE_PIC,
};
export const Android_Theme_Dark = { 


};
export const IOS_Theme_Light = {

    //SVG ICONS
    ICON_BACK_ARROW : images.ICON_BACK_ARROW_IOS_LIGHT

};
export const IOS_Theme_Dark = {

};
