import Colors from "./Colors";
import Fonts from "./Fonts";
import images from "./Images";

export const Android_Theme_Light = {

  //COMMON COLORS
  WHITE_COLOR: Colors.WHITE,
  BACKGROUND_COLOR: Colors.BLUE_ACCENT,
  SAFEAREA_BACKGROUND_COLOR: Colors.BLUE_ACCENT,
  COMMON_BUTTON_BACKGROUND_COLOR: Colors.Dark_Blue,

  //FONT TYPES
  POPPINS_THIN: Fonts.POPPINS_THIN,
  POPPINS_LIGHT: Fonts.POPPINS_LIGHT,
  POPPINS_REGULAR: Fonts.POPPINS_REGULAR,
  POPPINS_MEDIUM: Fonts.POPPINS_MEDIUM,
  POPPINS_SEMIBOLD: Fonts.POPPINS_SEMIBOLD,
  POPPINS_BOLD: Fonts.POPPINS_BOLD,
  POPPINS_EXTRABOLD: Fonts.POPPINS_EXTRABOLD,
  POPPINS_THINITALIC: Fonts.POPPINS_THINITALIC,
  POPPINS_LIGHTITALIC: Fonts.POPPINS_LIGHTITALIC,
  POPPINS_MEDIUM_ITALIC: Fonts.POPPINS_MEDIUM_ITALIC,
  POPPINS_SEMIBOLD_ITALIC: Fonts.POPPINS_SEMIBOLD_ITALIC,
  POPPINS_BOLD_ITALIC: Fonts.POPPINS_BOLD_ITALIC,
  POPPINS_EXTRABOLD_ITALIC: Fonts.POPPINS_EXTRABOLD_ITALIC,


  //Text Style Colors
  TextStyleH1Color : Colors.BLACK_DEEP,
  TextStyleH3Color: Colors.BLACK_DEEP,
  TextStyleCaptionColor: Colors.GRAY_DARK,
  TextStyleH1MediumColor : Colors.GRAY,
  TEXTSTYLE_BODY_COLOR : Colors.GRAY
 
};
export const Android_Theme_Dark = {


};
export const IOS_Theme_Light = {

};
export const IOS_Theme_Dark = {

};
